// Mocks generated by Mockito 5.2.0 from annotations
// in bmi_calculator/test/blocs_test/bmi_bloc_test/bmi_bloc_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i5;

import 'package:bmi_calculator/infrastructure/datasources/repositories/bmi_repository.dart'
    as _i4;
import 'package:bmi_calculator/infrastructure/models/bmi_model.dart' as _i3;
import 'package:dio/dio.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types

class _FakeDio_0 extends _i1.Fake implements _i2.Dio {}

class _FakeBmiModel_1 extends _i1.Fake implements _i3.BmiModel {}

/// A class which mocks [BmiRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockBmiRepository extends _i1.Mock implements _i4.BmiRepository {
  MockBmiRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.Dio get dio =>
      (super.noSuchMethod(Invocation.getter(#dio), returnValue: _FakeDio_0())
          as _i2.Dio);
  @override
  _i5.Future<_i3.BmiModel> calculateBmi({int? height, int? weight, int? age}) =>
      (super.noSuchMethod(
              Invocation.method(#calculateBmi, [],
                  {#height: height, #weight: weight, #age: age}),
              returnValue: Future<_i3.BmiModel>.value(_FakeBmiModel_1()))
          as _i5.Future<_i3.BmiModel>);
}
